services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=vou-marketing
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d vou-marketing"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" # Port AMQP
      - "15672:15672" # Port Management UI (Web)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Volume cho dữ liệu của RabbitMQ

  # auth:
  #   build: 
  #     context: .
  #     dockerfile: ./docker/Dockerfile-auth
  #   ports:
  #     - "50051:50051"
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/vou-marketing?sslmode=disable
  #     - REDIS_ADDRESS=redis:6379
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  # counterpart:
  #   build: 
  #     context: .
  #     dockerfile: ./docker/Dockerfile-counterpart
  #   ports:
  #     - "50052:50052"
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/vou-marketing?sslmode=disable
  # gateway:
  #   build: 
  #     context: .
  #     dockerfile: ./docker/Dockerfile-gateway
  #   ports:
  #     - "8080:8080"
  #     - "9090:9090"
  #   environment:
  #     - AUTH_SERVER_ADDRESS=auth:50051
  #     - COUNTERPART_SERVER_ADDRESS=counterpart:50052
  #   depends_on:
  #     - auth
  #     - counterpart
volumes:
  data-volume:
  rabbitmq_data: 