// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: event.sql

package db

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
  game_id,
  store_id,
  name,
  photo,
  voucher_quantity,
  status,
  start_time,
  end_time
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, game_id, store_id, name, photo, voucher_quantity, status, start_time, end_time
`

type CreateEventParams struct {
	GameID          int64        `json:"game_id"`
	StoreID         int64        `json:"store_id"`
	Name            string       `json:"name"`
	Photo           string       `json:"photo"`
	VoucherQuantity int32        `json:"voucher_quantity"`
	Status          EventsStatus `json:"status"`
	StartTime       time.Time    `json:"start_time"`
	EndTime         time.Time    `json:"end_time"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.GameID,
		arg.StoreID,
		arg.Name,
		arg.Photo,
		arg.VoucherQuantity,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.StoreID,
		&i.Name,
		&i.Photo,
		&i.VoucherQuantity,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}
