// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: voucher.sql

package db

import (
	"context"
)

const listMyVouchers = `-- name: ListMyVouchers :many
SELECT V.id, V.event_id, V.qr_code, V.type, V.status, V.expires_at, V.discount
FROM voucher_owner O, vouchers V
WHERE O.voucher_id = V.id AND O.username = $1
`

func (q *Queries) ListMyVouchers(ctx context.Context, username string) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, listMyVouchers, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voucher{}
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.QrCode,
			&i.Type,
			&i.Status,
			&i.ExpiresAt,
			&i.Discount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
