# Build stage
FROM golang:1.23-alpine3.20 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o auth-service ./cmd/auth/main.go

# Use a smaller base image for the final image
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/auth-service .
COPY cmd/auth/config/app.env ./config/
COPY db/migration ./db/migration

# Expose the port the service runs on
EXPOSE 50051

# Command to run the executable
CMD ["/app/auth-service"]

# docker build -t auth-service:latest -f docker/Dockerfile-auth .
# docker run --name auth -p 50051:50051 auth-service:latest
# docker run --name auth --network vou-network -p 50051:50051 auth-service:latest
