# Build stage
FROM golang:1.23-alpine3.20 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o game-service ./cmd/game/main.go

# Use a smaller base image for the final image
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/game-service .
COPY cmd/game/config/app.env ./config/

# Expose the port the service runs on
EXPOSE 50054

# Command to run the executable
CMD ["/app/game-service"]

# docker build -t game-service:latest -f docker/Dockerfile-game .
# docker run --name game -p 50054:50054 game-service:latest
# docker run --name game --network vou-network -p 50054:50054 game-service:latest
