# Build stage
FROM golang:1.23-alpine3.20 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o gateway-service ./cmd/gateway/main.go

# Use a smaller base image for the final image
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/gateway-service .
COPY cmd/gateway/config/app.env ./config/

# Expose the port the service runs on
EXPOSE 8080

# Command to run the executable
CMD ["/app/gateway-service"]

# docker build -t gateway-service:latest -f docker/Dockerfile-gateway .
# docker run --name gateway -p 8080:8080 gateway-service:latest
# docker run --name gateway --network vou-network -p 8080:8080 gateway-service:latest
