# Build stage
FROM golang:1.23-alpine3.20 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o event-service ./cmd/event/main.go

# Use a smaller base image for the final image
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/event-service .
COPY cmd/event/config/app.env ./config/

# Expose the port the service runs on
EXPOSE 50053

# Command to run the executable
CMD ["/app/event-service"]

# docker build -t event-service:latest -f docker/Dockerfile-event .
# docker run --name event -p 50052:50052 event-service:latest
# docker run --name event --network vou-network -p 50052:50052 event-service:latest
